[build-system]
requires = ["setuptools"]

[project]
name = "barcocollab"
version = "0.1.0"
description = "A very basic stub Python package named barcocollab deployed to protect a package released to an internal company pypi index"
readme = "README.md"
requires-python = ">=3.6"